### ISSUE TITLE
Ikonbruk for web

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/grafiskprofil#1]
### Nåværende løsning
A) Nå benyttes det ikoner fra flere kilder som en del av nettsideløsningene. For å få bedre kontinuitet foreslås det å benytte de samme ikonsettene på tvers av prosjektene og innad i prosjektene. 
B) Det benyttes ikke nødvendigvis de samme ikonene til samme funksjon eller aksjon på forskjellige steder. Et ikon som brukes til noe en plass, bør ikke brukes til noe annet en annen plass. Dette øker gjenkjenneligheten.
C) Det er ikke konsekvent hvordan ikon benyttes sammen med eller i steden for tekst. Se universell utforming.
D) Størrelse og kompleksitet: et større ikon er ofte mer komplekst enn et lite. Vi kan ikke nødvendigvis bruke de samme ikonene i stort og smått. Spesielt gjelder dette der vi har avanserte ikon, så kan ikke de nødvendigvis krympes og likevel være effektive.
E) Hvordan håndtere at et ikon er en lenke eller om det kun er informativt

### Bakgrunnsinformasjon andre bør lese før de kommenterer
- https://uxplanet.org/icons-as-part-of-an-awesome-user-experience-e468e16b206b
- https://material.io/tools/icons/?style=baseline

### Forslag til løsninger
A) Helene og Bjørn foreslår å benytte Material Icons https://material.io/tools/icons/?style=baseline som ikonbibliotek, men supplere med andre løsninger der det mangler noe.
  * Dette biblioteket er lett å bruke som både font og svg
  * Meget dekkende for kart og andre brukersituasjoner vi har
  * Allerede innebygd i f.eks React, og tatt i bruk i NiN-kart.
  * Siden det er kjent og utviklat av Google, er det mange som kjenner disse ikonene godt fra før.
  * Gratis

B) Gjennomgang av alle prosjektene for å finne likheter og ulikheter. Se hvordan man har løst det, og velge ét ikon for en aktivitet. Hvem ønsker å ta del i dette? La oss starte med noen enkle ikon og ta det derfra. Utarbeid wiki samtidig som man blir enig.

**Comment by runningbones** [comment]
Kan være fornuftig å tidlig avklare hvor egenproduserte ikoner skal forvaltes/lagres/hentes.

**Comment by helemork** [comment]
**Format**
Helt enig, @runningbones, og det et også viktig å avklare **hvilke format** vi ønsker å ha dem i. Svg er jo flott for ikoner i seg selv så de kan endre farge osv, men for ting fargen er konstant er det kanskje hensiktsmessig å ha bildefiler (transparent png f.eks). 

**Lagres og hentes**
De burde uansett kunne lastes ned fra data.artsdatabanken.no, så å ha dem tilgjengelige der er bra. 
Men det er jo enda bedre om vi gjør det lett for alle å kunne laste opp egne når vi har noen. 

**Lisenser**
Vi må også avklare lisens på det vi lager av eget - tillater vi gjenbruk eller ikke osv.

**Comment by bjornreppen** [comment]
Jeg undersøker mulighet for konvertering av eksisterende ikoner til SVG
