### ISSUE TITLE
Lenkene fungerer ikke lenger

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/grafiskprofil#15]
Lenkene under design.artsdatabanken.no har sluttet å fungere. Dvs. man kan gå direkte til en ressurs, men man får ikke se katalogene. 
Denne fungerer altså: https://design.artsdatabanken.no/icons/adb-logo/Artsdatabanken_Logo-CMYK-H-Colour@2x.png
mens denne ikke gjør det (404): https://design.artsdatabanken.no/icons

**Comment by Myrdrahl** [comment]
Har sett litt på dette med "directory browsing" i $web, men ikke klart å få det til å funke. Har derfor laget en liten hack, https://design.test.artsdatabanken.no/struktur.html. FIlen genereres ved bygg og viser derfor filene og katalogene slik de faktisk er.
