### ISSUE TITLE
Tastaturnavigering (meny)

### ISSUE THREAD

**Issue by danam2** [Artsdatabanken/grafiskprofil#3]
Man skal navigere seg gjennom Hovedmenyen ved bruk av tab.
Undermenyen åpnes med Enter og man navigerer seg ned med tab.

Anbefalt av Andreas Cederbom (ekspert for universell utforming)

**Comment by helemork** [comment]
La dette inn i wikien her: 
https://github.com/Artsdatabanken/grafiskprofil/wiki/Tastaturnavigering

Refererer relaterte issues i andre prosjekt dit.

**Comment by helemork** [comment]
For å unngå fremtidig forvirring:
-  Tastaturnavigering(meny): i Norge brukes taber for å navigere gjennom hoveds-meny/navigeringsmeny, piler er forheholdt andre ting, Eksempel på meny navigering https://www.regjeringen.no/
- I søkeresultat/dropdown og andre typer element er piler greit. Dette er ikke ansett som menynavigering, til tross for at også det er en type meny.
